//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;


namespace ET
{
   
public partial class Tables
{
    public AIConfigCategory AIConfigCategory {get; }
    public UnitConfigCategory UnitConfigCategory {get; }
    public ServerInfoConfigCategory ServerInfoConfigCategory {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        AIConfigCategory = new AIConfigCategory(loader("aiconfigcategory")); 
        tables.Add("AIConfigCategory", AIConfigCategory);
        UnitConfigCategory = new UnitConfigCategory(loader("unitconfigcategory")); 
        tables.Add("UnitConfigCategory", UnitConfigCategory);
        ServerInfoConfigCategory = new ServerInfoConfigCategory(loader("serverinfoconfigcategory")); 
        tables.Add("ServerInfoConfigCategory", ServerInfoConfigCategory);

        PostInit();
        AIConfigCategory.Resolve(tables); 
        UnitConfigCategory.Resolve(tables); 
        ServerInfoConfigCategory.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        AIConfigCategory.TranslateText(translator); 
        UnitConfigCategory.TranslateText(translator); 
        ServerInfoConfigCategory.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}