//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using System;


namespace ET.ConfigEditor
{

[Serializable]
public sealed partial class NumericInfoList :  Bright.Config.EditorBeanBase 
{
    public NumericInfoList()
    {
            List = new System.Collections.Generic.List<NumericInfo>();
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["list"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } List = new System.Collections.Generic.List<NumericInfo>(); foreach(JSONNode __e in _fieldJson.Children) { NumericInfo __v;  if(!__e.IsObject) { throw new SerializationException(); }  __v = NumericInfo.LoadJsonNumericInfo(__e);  List.Add(__v); }  
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        _json["$type"] = "NumericInfoList";
        {

            if (List == null) { throw new System.ArgumentNullException(); }
            { var __cjson = new JSONArray(); foreach(var _e in List) { { var __bjson = new JSONObject();  NumericInfo.SaveJsonNumericInfo(_e, __bjson); __cjson["null"] = __bjson; } } _json["list"] = __cjson; }
        }
    }

    public static NumericInfoList LoadJsonNumericInfoList(SimpleJSON.JSONNode _json)
    {
        NumericInfoList obj = new NumericInfoList();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonNumericInfoList(NumericInfoList _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    public System.Collections.Generic.List<NumericInfo> List;

}
}
