//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using System;


namespace ET.ConfigEditor
{

[Serializable]
public sealed partial class StartProcessConfig :  Bright.Config.EditorBeanBase 
{
    public StartProcessConfig()
    {
            AppName = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["MachineId"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  MachineId = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["InnerPort"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  InnerPort = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["AppName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  AppName = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {
            _json["MachineId"] = new JSONNumber(MachineId);
        }
        {
            _json["InnerPort"] = new JSONNumber(InnerPort);
        }
        {

            if (AppName == null) { throw new System.ArgumentNullException(); }
            _json["AppName"] = new JSONString(AppName);
        }
    }

    public static StartProcessConfig LoadJsonStartProcessConfig(SimpleJSON.JSONNode _json)
    {
        StartProcessConfig obj = new StartProcessConfig();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonStartProcessConfig(StartProcessConfig _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id;

    /// <summary>
    /// 所属机器
    /// </summary>
    public int MachineId;

    /// <summary>
    /// 内网端口
    /// </summary>
    public int InnerPort;

    /// <summary>
    /// 程序名
    /// </summary>
    public string AppName;

}
}
