//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;
using System;


namespace ET.ConfigEditor
{

[Serializable]
public sealed partial class StartMachineConfig :  Bright.Config.EditorBeanBase 
{
    public StartMachineConfig()
    {
            InnerIP = "";
            OuterIP = "";
            WatcherPort = "";
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["InnerIP"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  InnerIP = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["OuterIP"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  OuterIP = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["WatcherPort"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  WatcherPort = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {

            if (InnerIP == null) { throw new System.ArgumentNullException(); }
            _json["InnerIP"] = new JSONString(InnerIP);
        }
        {

            if (OuterIP == null) { throw new System.ArgumentNullException(); }
            _json["OuterIP"] = new JSONString(OuterIP);
        }
        {

            if (WatcherPort == null) { throw new System.ArgumentNullException(); }
            _json["WatcherPort"] = new JSONString(WatcherPort);
        }
    }

    public static StartMachineConfig LoadJsonStartMachineConfig(SimpleJSON.JSONNode _json)
    {
        StartMachineConfig obj = new StartMachineConfig();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonStartMachineConfig(StartMachineConfig _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id;

    /// <summary>
    /// 内网地址
    /// </summary>
    public string InnerIP;

    /// <summary>
    /// 外网地址
    /// </summary>
    public string OuterIP;

    /// <summary>
    /// 守护进程端口
    /// </summary>
    public string WatcherPort;

}
}
