//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET
{
   
public partial class PlayerNumericConfigCatrgory
{
    private readonly Dictionary<int, PlayerNumericConfig> _dataMap;
    private readonly List<PlayerNumericConfig> _dataList;
    
    public PlayerNumericConfigCatrgory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, PlayerNumericConfig>();
        _dataList = new List<PlayerNumericConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            PlayerNumericConfig _v;
            _v = PlayerNumericConfig.DeserializePlayerNumericConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, PlayerNumericConfig> DataMap => _dataMap;
    public List<PlayerNumericConfig> DataList => _dataList;

    public PlayerNumericConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PlayerNumericConfig Get(int key) => _dataMap[key];
    public PlayerNumericConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}