//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace ET
{

public sealed partial class StartZoneConfig :  Bright.Config.BeanBase 
{
    public StartZoneConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ZoneType = _buf.ReadInt();
        DBName = _buf.ReadString();
        DBConnection = _buf.ReadString();
        PostInit();
    }

    public static StartZoneConfig DeserializeStartZoneConfig(ByteBuf _buf)
    {
        return new StartZoneConfig(_buf);
    }

    /// <summary>
    /// 区服Id 最大1024个
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 区服类型
    /// </summary>
    public int ZoneType { get; private set; }
    /// <summary>
    /// 数据库名
    /// </summary>
    public string DBName { get; private set; }
    /// <summary>
    /// 数据库地址
    /// </summary>
    public string DBConnection { get; private set; }

    public const int __ID__ = -457316368;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ZoneType:" + ZoneType + ","
        + "DBName:" + DBName + ","
        + "DBConnection:" + DBConnection + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
